# Generated by Django 4.1.7 on 2023-04-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gear_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=30)),
                ('client_email', models.EmailField(max_length=254)),
                ('order_name', models.TextField()),
                ('order_drawing', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Rack_neck_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=30)),
                ('client_email', models.EmailField(max_length=254)),
                ('order_name', models.TextField()),
                ('order_drawing', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Worm_gear_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=30)),
                ('client_email', models.EmailField(max_length=254)),
                ('order_name', models.TextField()),
                ('order_drawing', models.ImageField(upload_to='')),
            ],
        ),
    ]
